apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: minhpham95
spec:
  profile:
    # Intentional no displayName for testing
    email: breanna-davison@example.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Luna&backgroundColor=transparent
  memberOf: [development]
